package controllertest;

import org.junit.Before;
import org.junit.Test;

import java.io.StringReader;

import controller.DungeonConsoleController;
import controller.DungeonController;
import dungeon.Dungeon;
import dungeon.DungeonImpl;
import location.Location;
import player.Player;
import player.PlayerImpl;
import weapon.Arrow;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

/**
 * Class for testing the Dungeon Controller.
 */
public class DungeonControllerTest {

  private Player player;
  private Dungeon model;

  @Before
  public void setup() {
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 5, true, player, 45);
    model.assignMonsters(8);
    model.assignTreasuresAndWeapons(55);
  }

  @Test(expected = IllegalStateException.class)
  public void testFailingAppendable() {
    // Testing when something goes wrong with the Appendable
    // Here we are passing it a mock of an Appendable that always fails
    StringReader input = new StringReader("M A");
    Appendable gameLog = new FailingAppendable();
    DungeonController controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
  }

  @Test(expected = IllegalArgumentException.class)
  public void testInvalidModel() {
    StringReader input = new StringReader("2 2");
    Appendable gameLog = new StringBuilder();
    DungeonController controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(null);
  }

  @Test
  public void testControllerWithMock() {
    StringBuilder log = new StringBuilder();
    //testing all moves ,pickup and shoot.
    StringReader input = new StringReader("M A M W M S M D P"
                                          + " treasure P arrow "
                                          + "S W 2 S W 3 S A 2 "
                                          + "S A 3 S D 2 S D 3 "
                                          + "S S 1 S S 2");
    Appendable gameLog = new StringBuilder();
    Dungeon model = new MockModel(log);
    DungeonController controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    String res = "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "Direction: WEST\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "Direction: NORTH\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "Direction: SOUTH\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "Direction: EAST\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "pickupTreasures\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "pickupArrows\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "canShoot\n"
                 + "Distance: 2\n"
                 + "Direction: NORTH\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "canShoot\n"
                 + "Distance: 3\n"
                 + "Direction: NORTH\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "canShoot\n"
                 + "Distance: 2\n"
                 + "Direction: WEST\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "canShoot\n"
                 + "Distance: 3\n"
                 + "Direction: WEST\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "canShoot\n"
                 + "Distance: 2\n"
                 + "Direction: EAST\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "canShoot\n"
                 + "Distance: 3\n"
                 + "Direction: EAST\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "canShoot\n"
                 + "Distance: 1\n"
                 + "Direction: SOUTH\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n"
                 + "canShoot\n"
                 + "Distance: 2\n"
                 + "Direction: SOUTH\n"
                 + "isGameOver\n"
                 + "detectStrongSmell\n"
                 + "detectWeakSmell\n";
    assertEquals(res, log.toString());
    assertEquals("Welcome to the Dangerous Cave \n"
                 + "Get Ready for the adventure \n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Invalid Move\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Invalid Move\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Invalid Move\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Invalid Move\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the treasures in that location.\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Description\n"
                 + "\n"
                 + "Player Description\n"
                 + "\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n", gameLog.toString());
  }


  @Test
  public void testMove() {
    //tests in this.
    //1. reach end location.
    //2. perform an invalid move.
    //3. test smell in the location.
    StringReader input = new StringReader("S A 1"
                                          + " S A 1 "
                                          + "M A P "
                                          + "arrow S"
                                          + " A 1 S A"
                                          + " 1 M A M"
                                          + " S P arrow"
                                          + " M S M A "
                                          + "S S 1 S "
                                          + "S 1 M A "
                                          + "M S");
    Appendable gameLog = new StringBuilder();
    DungeonController controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    String res = "Welcome to the Dangerous Cave \n"
                 + "Get Ready for the adventure \n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (2,4)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (2,4)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (2,4)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: WEST\n"
                 + "\n"
                 + "Location Treasures: [SAPPHIRE, RUBY, DIAMOND] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (2,3)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Treasures: [SAPPHIRE, RUBY, DIAMOND] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (2,3)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [SAPPHIRE, RUBY, DIAMOND] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (2,3)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [SAPPHIRE, RUBY, DIAMOND] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (2,3)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: WEST\n"
                 + "\n"
                 + "Location Treasures: [SAPPHIRE, SAPPHIRE] \n"
                 + "Location Arrows: [CROOKED]\n"
                 + "Location Valid Moves: [SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (2,2)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: SOUTH\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (3,2)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (3,2)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: SOUTH\n"
                 + "\n"
                 + "Location Treasures: [DIAMOND, DIAMOND] \n"
                 + "Location Arrows: [CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,2)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Invalid Move\n"
                 + "\n"
                 + "Location Treasures: [DIAMOND, DIAMOND] \n"
                 + "Location Arrows: [CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,2)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [DIAMOND, DIAMOND] \n"
                 + "Location Arrows: [CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,2)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [DIAMOND, DIAMOND] \n"
                 + "Location Arrows: [CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,2)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Invalid Move\n"
                 + "\n"
                 + "Location Treasures: [DIAMOND, DIAMOND] \n"
                 + "Location Arrows: [CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,2)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: SOUTH\n"
                 + "Game is Over.You have reached the end. and won the game.";
    assertEquals(res, gameLog.toString());
    assertTrue(model.isGoalState());
    assertTrue(model.isGameOver());

    //testing move
    //this test includes the following.
    //1.player dies entering a monster cave.
    //setup
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 5, true, player, 45);
    model.assignMonsters(8);
    model.assignTreasuresAndWeapons(55);
    input = new StringReader("M A");
    gameLog = new StringBuilder();
    controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    //checking if the model actually changed current
    res = "Welcome to the Dangerous Cave \n"
          + "Get Ready for the adventure \n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: WEST\n"
          + "Game is Over.You have been slayed.";
    assertEquals(res, gameLog.toString());
    assertEquals(model.getCurrentLocation().getXLocation(), 2);
    assertEquals(model.getCurrentLocation().getYLocation(), 3);
    assertTrue(model.isGameOver());
    assertFalse(model.isGoalState());

    //testing move
    //this test includes the following.
    //1.player survives entering an injured monster cave.
    //setup
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 5, true, player, 45);
    model.assignMonsters(8);
    model.assignTreasuresAndWeapons(55);

    input = new StringReader("S A 1 M A");
    gameLog = new StringBuilder();
    controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    res = "Welcome to the Dangerous Cave \n"
          + "Get Ready for the adventure \n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East.\n"
          + "\n"
          + "Enter positive distance.\n"
          + "There is a huge Growl. You have hit something.\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: WEST\n"
          + "\n"
          + "Location Treasures: [SAPPHIRE, RUBY, DIAMOND] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,3)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "Weak monster smell detected. Beware X\n";
    assertEquals(res, gameLog.toString());
    //asserting if we really made a move.
    assertEquals(model.getCurrentLocation().getXLocation(), 2);
    assertEquals(model.getCurrentLocation().getYLocation(), 3);
    assertTrue(model.getCurrentLocation().getMonsters().size() > 0);
    assertTrue(model.getCurrentLocation().getMonsters().get(0).getHealth() == 1);
    assertFalse(model.isGameOver());
    assertFalse(model.isGoalState());

    //testing move
    //this test includes the following.
    //1.player dies entering an injured monster cave.
    //setup
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5,
            5,
            5,
            true,
            player,
            45);
    model.assignMonsters(8);
    model.assignTreasuresAndWeapons(55);
    input = new StringReader("S A 1 "
                             + "M A M "
                             + "D M A "
                             + "M D M "
                             + "A M D "
                             + "M A M "
                             + "D M A");
    gameLog = new StringBuilder();
    controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    //assert end location.
    Location[][] locations = model.getLocationGrid();
    Location endLocation = model.getEndLocation();
    assertTrue(locations[endLocation.getXLocation()]
                       [endLocation.getYLocation()].getMonsters().size() > 0);

    res = "Welcome to the Dangerous Cave \n"
          + "Get Ready for the adventure \n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East.\n"
          + "\n"
          + "Enter positive distance.\n"
          + "There is a huge Growl. You have hit something.\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: WEST\n"
          + "\n"
          + "Location Treasures: [SAPPHIRE, RUBY, DIAMOND] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,3)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "Weak monster smell detected. Beware X\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: EAST\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: WEST\n"
          + "\n"
          + "Location Treasures: [SAPPHIRE, RUBY, DIAMOND] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,3)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "Weak monster smell detected. Beware X\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: EAST\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: WEST\n"
          + "\n"
          + "Location Treasures: [SAPPHIRE, RUBY, DIAMOND] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,3)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "Weak monster smell detected. Beware X\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: EAST\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: WEST\n"
          + "\n"
          + "Location Treasures: [SAPPHIRE, RUBY, DIAMOND] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,3)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "Weak monster smell detected. Beware X\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: EAST\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: [CROOKED, CROOKED]\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (2,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=2}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "Strong monster smell detected. Beware XX\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: WEST\n"
          + "Game is Over.You have been slayed.";
    assertEquals(res, gameLog.toString());
    assertEquals(model.getCurrentLocation().getXLocation(), 2);
    assertEquals(model.getCurrentLocation().getYLocation(), 3);
    assertTrue(model.getCurrentLocation().getMonsters().size() > 0);
    assertTrue(model.getCurrentLocation().getMonsters().get(0).getHealth() == 1);
    assertTrue(model.isGameOver());
    assertFalse(model.isGoalState());

    //move all directions
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 24, true, player, 45);
    input = new StringReader("M W M S M D M A M W");
    gameLog = new StringBuilder();
    controller = new DungeonConsoleController(input, gameLog);
    assertEquals(model.getCurrentLocation().getXLocation(), 1);
    assertEquals(model.getCurrentLocation().getYLocation(), 4);
    controller.playDungeonGame(model);
    res = "Welcome to the Dangerous Cave \n"
          + "Get Ready for the adventure \n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (1,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: NORTH\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (0,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: SOUTH\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (1,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: EAST\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (1,0)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: WEST\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (1,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n\n\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Move Successful: NORTH\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (0,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n";
    assertEquals(res, gameLog.toString());
    assertEquals(model.getCurrentLocation().getXLocation(), 0);
    assertEquals(model.getCurrentLocation().getYLocation(), 4);

    //test Invalid input for move
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 24, true, player, 45);
    input = new StringReader("M G M L M H M R");
    gameLog = new StringBuilder();
    controller = new DungeonConsoleController(input, gameLog);
    assertEquals(model.getCurrentLocation().getXLocation(), 1);
    assertEquals(model.getCurrentLocation().getYLocation(), 4);
    controller.playDungeonGame(model);
    res = "Welcome to the Dangerous Cave \n"
          + "Get Ready for the adventure \n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (1,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Invalid input\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (1,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Invalid input\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (1,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Invalid input\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (1,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n"
          + "\n"
          + "Enter W,A,S,D for North,West,South,East .\n"
          + "Invalid input\n"
          + "\n"
          + "Location Treasures: [] \n"
          + "Location Arrows: []\n"
          + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
          + "\n"
          + "Player : Mario \n"
          + "Player Coordinates: (1,4)\n"
          + "Player Treasures: {}\n"
          + "Player Arrows: {CROOKED=3}\n"
          + "The player has the following actions: \n"
          + "Move, Pickup, or Shoot (M-P-S)\n"
          + "\n";
    assertEquals(res, gameLog.toString());
    assertEquals(model.getCurrentLocation().getXLocation(), 1);
    assertEquals(model.getCurrentLocation().getYLocation(), 4);
  }

  //testPickUp.
  @Test
  public void testPickupArrowsAndTreasures() {
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 6, 24, true, player, 45);
    model.assignTreasuresAndWeapons(65);
    model.assignMonsters(3);
    //1.picking treasures and arrows in the locations.
    Readable input = new StringReader("P arrow M A P treasure M A P arrow P treasure");
    Appendable gameLog = new StringBuilder();
    DungeonController controller = new DungeonConsoleController(input, gameLog);
    Location[][] locations = model.getLocationGrid();
    assertTrue(locations[1][4].getArrows().size() == 2);
    assertTrue(locations[1][3].getTreasures().size() == 2);
    assertTrue(locations[1][2].getTreasures().size() == 2);
    assertTrue(locations[1][2].getArrows().size() == 1);
    assertTrue(player.getArrows().get(Arrow.CROOKED) == 3);
    assertTrue(player.getTreasures().size() == 0);


    controller.playDungeonGame(model);

    assertEquals("Welcome to the Dangerous Cave \n"
                 + "Get Ready for the adventure \n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,4)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,4)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=5}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: WEST\n"
                 + "\n"
                 + "Location Treasures: [DIAMOND, SAPPHIRE] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,3)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=5}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the treasures in that location.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,3)\n"
                 + "Player Treasures: {DIAMOND=1, SAPPHIRE=1}\n"
                 + "Player Arrows: {CROOKED=5}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: WEST\n"
                 + "\n"
                 + "Location Treasures: [RUBY, SAPPHIRE] \n"
                 + "Location Arrows: [CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,2)\n"
                 + "Player Treasures: {DIAMOND=1, SAPPHIRE=1}\n"
                 + "Player Arrows: {CROOKED=5}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Treasures: [RUBY, SAPPHIRE] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,2)\n"
                 + "Player Treasures: {DIAMOND=1, SAPPHIRE=1}\n"
                 + "Player Arrows: {CROOKED=6}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the treasures in that location.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,2)\n"
                 + "Player Treasures: {DIAMOND=1, RUBY=1, SAPPHIRE=2}\n"
                 + "Player Arrows: {CROOKED=6}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n\n", gameLog.toString());
    locations = model.getLocationGrid();
    assertTrue(locations[1][4].getArrows().size() == 0);
    assertTrue(locations[1][3].getTreasures().size() == 0);
    assertTrue(locations[1][2].getTreasures().size() == 0);
    assertTrue(locations[1][2].getArrows().size() == 0);
    assertTrue(player.getArrows().get(Arrow.CROOKED) == 6);
    assertTrue(player.getTreasures().size() == 4);

    //test invalid input
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 6, 24, true, player, 45);
    model.assignTreasuresAndWeapons(65);
    model.assignMonsters(3);
    //1.picking treasures and arrows in the locations.
    String intial = model.toString();
    input = new StringReader("P lol P jols P tooot");
    gameLog = new StringBuilder();
    controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    String result = model.toString();
    assertEquals(intial, result);
    assertEquals("Welcome to the Dangerous Cave \n"
                 + "Get Ready for the adventure \n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,4)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "Wrong Input for Pickup. Try Again.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,4)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "Wrong Input for Pickup. Try Again.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,4)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "Wrong Input for Pickup. Try Again.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,4)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n", gameLog.toString());

  }

  @Test
  public void testArrowShooting() {
    //1. arrow shooting at a distance 1.
    //2. arrow shooting at a distance 2.
    //3. arrow missing.
    //4.invalid input.
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 10, false, player, 5);
    model.assignTreasuresAndWeapons(50);
    model.assignMonsters(10);
    Location[][] locations = model.getLocationGrid();
    assertTrue(locations[2][0].getMonsters().size() > 0);
    assertTrue(locations[3][0].getMonsters().size() > 0);
    assertTrue(locations[3][1].getMonsters().size() > 0);
    Readable input = new StringReader("P arrow S S 1 S S 1 S S 2 S S 2 M S P "
                                      + "arrow M S P arrow S E 4 S D 4 S S 4 M S S"
                                      + " D 4 P arrow M D S W 1 S W 1");
    Appendable gameLog = new StringBuilder();
    DungeonController controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    assertEquals("Welcome to the Dangerous Cave \n"
                 + "Get Ready for the adventure \n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=5}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=4}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: SOUTH\n"
                 + "\n"
                 + "Location Treasures: [RUBY, RUBY] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (2,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Treasures: [RUBY, RUBY] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (2,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: SOUTH\n"
                 + "\n"
                 + "Location Treasures: [RUBY] \n"
                 + "Location Arrows: [CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (3,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Treasures: [RUBY] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (3,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=4}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "invalid direction\n"
                 + "\n"
                 + "Location Treasures: [RUBY] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (3,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=4}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Treasures: [RUBY] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (3,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [RUBY] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (3,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: SOUTH\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: EAST\n"
                 + "\n"
                 + "Location Treasures: [RUBY, DIAMOND, RUBY] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,1)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [RUBY, DIAMOND, RUBY] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,1)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [RUBY, DIAMOND, RUBY] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, EAST, WEST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (4,1)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n", gameLog.toString());

    assertEquals("0 0 [EAST, SOUTH] Tunnel [] Monsters :"
                 + " {} [CROOKED, CROOKED, CROOKED] 0 1 [WEST, EAST, SOUTH]"
                 + " Cave [RUBY, SAPPHIRE] Monsters : {} [CROOKED, CROOKED]"
                 + " 0 2 [WEST] Cave [RUBY, SAPPHIRE] "
                 + "Monsters : {} [CROOKED, CROOKED]"
                 + " 0 3 [SOUTH, EAST] Tunnel []"
                 + " Monsters : {} [CROOKED] 0 4 "
                 + "[WEST, SOUTH] Tunnel [] Monsters : {} [CROOKED] \n"
                 + "1 0 [NORTH, SOUTH, EAST] Cave []"
                 + " Monsters : {} [] 1 1 [SOUTH, EAST,"
                 + " NORTH, WEST] Cave [SAPPHIRE] Monsters : "
                 + "{} [CROOKED, CROOKED] 1 2 [SOUTH, WEST, EAST]"
                 + " Cave [] Monsters : {} [CROOKED, CROOKED]"
                 + " 1 3 [NORTH, EAST, WEST] Cave [RUBY, SAPPHIRE]"
                 + " Monsters : {} [CROOKED, CROOKED] 1 4 [SOUTH, WEST, NORTH]"
                 + " Cave [SAPPHIRE, SAPPHIRE]"
                 + " Monsters : {id : 7, health : 2. } [CROOKED] \n"
                 + "2 0 [SOUTH, EAST, NORTH] Cave [RUBY, RUBY] "
                 + "Monsters : {} [] 2 1 [EAST, NORTH, WEST, SOUTH] "
                 + "Cave [RUBY] Monsters : {} [CROOKED, CROOKED] 2 2 "
                 + "[NORTH, WEST, EAST] Cave [DIAMOND] "
                 + "Monsters : {id : 1, health : 2. } [] "
                 + "2 3 [EAST, WEST, SOUTH] Cave [SAPPHIRE, RUBY, DIAMOND]"
                 + " Monsters : {id : 6, health : 2. } [CROOKED, CROOKED] "
                 + "2 4 [NORTH, SOUTH, WEST] Cave [RUBY, SAPPHIRE] "
                 + "Monsters : {id : 0, health : 2. } [CROOKED, CROOKED] \n"
                 + "3 0 [NORTH, SOUTH, EAST] Cave [RUBY] Monsters : "
                 + "{} [] 3 1 [WEST, NORTH, EAST, SOUTH] Cave [SAPPHIRE] "
                 + "Monsters : {} [CROOKED, CROOKED] 3 2 [SOUTH, EAST, WEST]"
                 + " Cave [SAPPHIRE, DIAMOND] Monsters : {} [] 3 3 [SOUTH, WEST, NORTH]"
                 + " Cave [SAPPHIRE] Monsters : {} [CROOKED, CROOKED]"
                 + " 3 4 [NORTH] Cave [RUBY, DIAMOND] Monsters"
                 + " : {id : 9, health : 2. } [CROOKED, CROOKED] \n"
                 + "4 0 [NORTH, EAST] Tunnel []"
                 + " Monsters : {} [] 4 1 [EAST, NORTH, WEST]"
                 + " Cave [RUBY, DIAMOND, RUBY] Monsters"
                 + " : {} [CROOKED, CROOKED] 4 2 [NORTH, WEST, EAST]"
                 + " Cave [RUBY] Monsters : {} [CROOKED, CROOKED]"
                 + " 4 3 [NORTH, EAST, WEST] Cave [DIAMOND] "
                 + "Monsters : {id : 3, health : 2. } "
                 + "[CROOKED] 4 4 [WEST] Cave [RUBY, DIAMOND] "
                 + "Monsters : {} [] \n", model.toString());
    locations = model.getLocationGrid();
    assertFalse(locations[2][0].getMonsters().size() > 0);
    assertFalse(locations[3][0].getMonsters().size() > 0);
    assertFalse(locations[3][1].getMonsters().size() > 0);


    //multiple distances and tunnels
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 10, false, player, 5);
    model.assignTreasuresAndWeapons(50);
    model.assignMonsters(10);
    input = new StringReader("P arrow M W S S 7 S S 7");
    gameLog = new StringBuilder();
    locations = model.getLocationGrid();
    assertTrue(locations[4][4].getMonsters().size() > 0);
    controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    assertEquals("Welcome to the Dangerous Cave \n"
                 + "Get Ready for the adventure \n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=5}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East .\n"
                 + "Move Successful: NORTH\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (0,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=5}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (0,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=4}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (0,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n", gameLog.toString());
    locations = model.getLocationGrid();
    assertTrue(locations[4][4].getMonsters().size() == 0);


    //multiple distances and tunnels
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 10, false, player, 5);
    model.assignTreasuresAndWeapons(50);
    model.assignMonsters(10);
    input = new StringReader("P arrow S S 6 S S 6 S D 4 S D 4");
    gameLog = new StringBuilder();
    locations = model.getLocationGrid();
    assertTrue(locations[4][4].getMonsters().size() > 0);
    assertTrue(locations[1][4].getMonsters().size() > 0);
    controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    assertEquals("Welcome to the Dangerous Cave \n"
                 + "Get Ready for the adventure \n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter Arrow or Treasure.\n"
                 + "The player has picked up the arrows in that location.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=5}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=4}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: []\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n", gameLog.toString());
    locations = model.getLocationGrid();
    assertTrue(locations[4][4].getMonsters().size() == 0);
    assertTrue(locations[1][4].getMonsters().size() == 0);

    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 10, false, player, 5);
    model.assignTreasuresAndWeapons(50);
    model.assignMonsters(10);
    input = new StringReader("S S 3 S F -1 S G L");
    gameLog = new StringBuilder();
    controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    //arrow misses and invalid direction.
    //player at 1,0 shoots an arrow at distance 3 south we observe it misses
    //live monsters ar 2,0 and 3,0
    locations = model.getLocationGrid();
    assertEquals(model.getCurrentLocation().getXLocation(), 1);
    assertEquals(model.getCurrentLocation().getYLocation(), 0);
    assertTrue(locations[2][0].getMonsters().size() > 0);
    assertTrue(locations[3][0].getMonsters().size() > 0);
    assertEquals("Welcome to the Dangerous Cave \n"
                 + "Get Ready for the adventure \n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "invalid direction\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "invalid direction\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n", gameLog.toString());

  }

  @Test
  public void testSmell() {
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 10, false, player, 5);
    model.assignTreasuresAndWeapons(50);
    model.assignMonsters(10);
    Readable input = new StringReader("M W");
    Appendable gameLog = new StringBuilder();
    Location[][] locations = model.getLocationGrid();
    DungeonController controller = new DungeonConsoleController(input, gameLog);

    assertTrue(model.detectWeakSmell());
    assertTrue(model.detectStrongSmell());

    controller.playDungeonGame(model);
    //only weak monster detected.
    assertTrue(model.detectWeakSmell());
    assertFalse(model.detectStrongSmell());

    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 10, false, player, 5);
    model.assignTreasuresAndWeapons(50);
    model.assignMonsters(10);
    input = new StringReader("M W M D");
    gameLog = new StringBuilder();
    locations = model.getLocationGrid();
    controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    assertFalse(model.detectWeakSmell());
    assertFalse(model.detectStrongSmell());

    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 10, false, player, 5);
    model.assignTreasuresAndWeapons(50);
    model.assignMonsters(10);
    input = new StringReader("M W M D M S S S 1 S S 1");
    gameLog = new StringBuilder();
    locations = model.getLocationGrid();
    controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    //multiple monsters 2 distance away.
    assertFalse(model.detectWeakSmell());
    assertTrue(model.detectStrongSmell());
  }

  @Test
  public void testOutOfArrows() {
    player = new PlayerImpl("Mario");
    model = new DungeonImpl(5, 5, 10, false, player, 5);
    model.assignTreasuresAndWeapons(50);
    model.assignMonsters(10);
    Readable input = new StringReader("S S 1 S S 1 S S 1 S S 1");
    Appendable gameLog = new StringBuilder();
    DungeonController controller = new DungeonConsoleController(input, gameLog);
    controller.playDungeonGame(model);
    assertEquals("Welcome to the Dangerous Cave \n"
                 + "Get Ready for the adventure \n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=3}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=2}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Strong monster smell detected. Beware XX\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "There is a huge Growl. You have hit something.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=1}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Arrow Shot into darkness.\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=0}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n"
                 + "\n"
                 + "Enter W,A,S,D for North,West,South,East.\n"
                 + "\n"
                 + "Enter positive distance.\n"
                 + "Out of Arrows. Explore Dungeon\n"
                 + "\n"
                 + "Location Treasures: [] \n"
                 + "Location Arrows: [CROOKED, CROOKED]\n"
                 + "Location Valid Moves: [NORTH, SOUTH, EAST] \n"
                 + "\n"
                 + "Player : Mario \n"
                 + "Player Coordinates: (1,0)\n"
                 + "Player Treasures: {}\n"
                 + "Player Arrows: {CROOKED=0}\n"
                 + "The player has the following actions: \n"
                 + "Move, Pickup, or Shoot (M-P-S)\n"
                 + "\n"
                 + "Weak monster smell detected. Beware X\n", gameLog.toString());
    assertFalse(model.canShoot());
  }


}
